In [1]:
import numpy as np
from sympy import *
from random import randint

In [50]:
class Gauss:

    def cambiarFilas(self, matriz, fila):
        cambio = 0
        for i in range(1, len(matriz) - fila):
            if matriz[fila + i][fila] != 0:
                cambio = i
                break
        
        if not cambio:
            return False
            
        fila1 = fila
        fila2 = fila + cambio

        temp = matriz[fila1].copy()
        matriz[fila1] = matriz[fila2]
        matriz[fila2] = temp
        return matriz

    def sumarFilas(self, matriz, fila):
        for i in range(1, len(matriz) -  fila):
            reduccion = matriz[fila][fila].copy()
            multiplo = -1*matriz[fila+i][fila].copy()
            matriz[fila + i] = matriz[fila+i] + matriz[fila] * multiplo / reduccion
        return matriz

    def checarCeros(self, matriz, fila):
        if matriz[fila][fila] == 0:
            return True
        return False

    def transformar(self, matriz):
        copia = matriz.copy()
        finalInv = matriz.copy()
        for i in range(0,len(matriz)):
            for j in range(0,len(matriz[0]) - 1):
                finalInv[i][j] = copia[i][-2-j]
        copia = finalInv.copy()
        for i in range(0,len(matriz)):
            finalInv[i] = copia[-1+-i]
        return finalInv

    def checarDim(self, matriz):
        filas = len(matriz)
        columnas = len(matriz[0])
        if filas < columnas - 1 or filas > columnas - 1:
            return False
        return True


    def Gauss(self, matriz):
        for fila in range(0,len(matriz)):
            if self.checarCeros(matriz, fila):
                matriz = self.cambiarFilas(matriz, fila)
                if not np.any(matriz):
                    return False
            self.sumarFilas(matriz, fila)
        return matriz



    def solucion(self, matriz):
        if not self.checarDim(matriz):
            print("La matriz no tiene solución")
            return False
        matriz = self.Gauss(matriz)
        # print(matriz)
        if not np.any(matriz):
            print("La matriz no tiene solución")
            return False
        matriz = self.transformar(matriz)
        # print(matriz)
        matriz = self.Gauss(matriz)
        # print(matriz)
        matriz = self.transformar(matriz)
        # print(matriz)
        resultados = []
        for i in range(0,len(matriz)):
            resultados.append(matriz[i][-1]/matriz[i][i])
        for i in range(0,len(resultados)):
            print(f"x{i} = {resultados[i]}")
        return matriz

In [51]:
def matrizAleatoria():
    filas = randint(1,6)
    columnas = randint(2,6)
    M = [[randint(0,9) for i in range(0,columnas)] for i in range(0,filas)]
    M = np.array(M, dtype=float)
    return M

In [79]:
def crearMatriz():
    filas = int(input("numero de filas: "))
    columnas = int(input("numero de columnas: "))
    matriz = []
    for i in range(0,filas):
        fila = []
        for j in range(0,columnas):
            fila.append(input(f"elemento x[{i}][{j}]: "))
        matriz.append(fila)
    return np.array(matriz, dtype=float)

In [80]:
M = crearMatriz()
M   

array([[1., 2., 3.],
       [1., 2., 3.]])

In [71]:
M = matrizAleatoria()
Gauss().solucion(M)

[[7. 5. 0. 3. 5.]
 [2. 1. 6. 4. 4.]
 [5. 8. 7. 1. 5.]
 [4. 0. 4. 4. 6.]]
x0 = 1.2374999999999996
x1 = -0.575
x2 = 0.5249999999999994
x3 = -0.2624999999999989


array([[ 7.00000000e+00, -8.88178420e-16,  0.00000000e+00,
        -3.60420228e-15,  8.66250000e+00],
       [ 0.00000000e+00, -4.28571429e-01,  0.00000000e+00,
        -3.08931624e-16,  2.46428571e-01],
       [ 0.00000000e+00,  0.00000000e+00,  6.90000000e+01,
         3.55271368e-15,  3.62250000e+01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -2.31884058e+00,  6.08695652e-01]])