In [1]:
import numpy as np
from random import randint

In [23]:
def matrizAleatoria(dim):
    return np.array([[randint(0,9) for i in range(0,dim)] for i in range(0,dim)], dtype=float)

def crearMatriz():
    dim = int(input('Dimensiones de la matriz cuadrada: '))
    matriz = np.empty(dim, dtype=float)
    for i in range(0,len(matriz)):
        for j in range(0,len(matriz)):
            matriz[i][j] = int(input(f'x[{i+1}][{j+1}] = '))
    return matriz

In [12]:
class Gauss:

    def cambiarFilas(self, matriz, fila):
        cambio = 0
        for i in range(1, len(matriz) - fila):
            if matriz[fila + i][fila] != 0:
                cambio = i
                break
        
        if not cambio:
            return False
            
        fila1 = fila
        fila2 = fila + cambio

        temp = matriz[fila1].copy()
        matriz[fila1] = matriz[fila2]
        matriz[fila2] = temp
        return matriz

    def sumarFilas(self, matriz, fila):
        for i in range(1, len(matriz) -  fila):
            reduccion = matriz[fila][fila].copy()
            multiplo = -1*matriz[fila+i][fila].copy()
            matriz[fila + i] = matriz[fila+i] + matriz[fila] * multiplo / reduccion
        return matriz

    def checarCeros(self, matriz, fila):
        if matriz[fila][fila] == 0:
            return True
        return False

    def transformar(self, matriz):
        copia = matriz.copy()
        finalInv = matriz.copy()
        for i in range(0,len(matriz)):
            finalInv[i] = copia[-1+-i]
        a = np.hsplit(finalInv, 2)[0]
        aCopia = a.copy()
        b = np.hsplit(finalInv, 2)[1]
        bCopia = b.copy()
        for i in range(0,len(a)):
            for j in range(0,len(a[0])):
                a[i][j] = aCopia[i][-1-j]
                b[i][j] = bCopia[i][-1-j]
        finalInv = np.concatenate((a,b), axis=1)
        return finalInv

    def Gauss(self, matriz):
        for fila in range(0,len(matriz)):
            if self.checarCeros(matriz, fila):
                matriz = self.cambiarFilas(matriz, fila)
                if not np.any(matriz):
                    return False
            self.sumarFilas(matriz, fila)
        return matriz

    def unos(self, matriz):
        for i in range(0,len(matriz)):
            matriz[i] /= matriz[i][i]
        return matriz


    def inversa(self, matriz):
        matriz = np.concatenate((matriz, np.identity(len(matriz))), axis=1)
        matriz = self.Gauss(matriz)
        if not np.any(matriz):
            print("La matriz no tiene solución")
            return False
        matriz = self.transformar(matriz)
        matriz = self.Gauss(matriz)
        matriz = self.transformar(matriz)
        matriz = self.unos(matriz)
        return np.hsplit(matriz, 2)[1]

In [18]:
M = matrizAleatoria(5)
M

array([[3., 5., 6., 5., 1.],
       [0., 3., 6., 8., 7.],
       [9., 4., 3., 8., 4.],
       [9., 5., 1., 9., 6.],
       [6., 4., 2., 3., 3.]])

In [19]:
print(Gauss().inversa(M))

[[-0.09777778 -0.02777778  0.22555556 -0.16111111  0.11888889]
 [ 0.22666667 -0.08333333 -0.44333333  0.31666667  0.07666667]
 [-0.02666667  0.08333333  0.24333333 -0.31666667  0.12333333]
 [ 0.10222222 -0.02777778  0.02555556  0.17222222 -0.34777778]
 [-0.19111111  0.13888889 -0.04777778 -0.06111111  0.25888889]]
